launchdarkly/launchpad-ui

.changeset/lazy-walls-collect.md, packages/menu/package.json, packages/navigation/package.json, pnpm-lock.yaml
Aligns Launchpad `react-router-dom` package with the core app, using 6.4.2.
=> fix(menu,navigation): pin reactrouterdom dep to 6.4.2

.changeset/odd-lemons-call.md, packages/avatar/src/styles/Avatar.module.css, packages/button/src/styles/Button.css, packages/chip/src/styles/Chip.module.css, packages/counter/src/styles/Counter.module.css, packages/modal/src/styles/Modal.module.css, packages/tab-list/src/styles/TabList.module.css, packages/table/src/styles/Table.module.css, packages/tokens/src/color.yaml
- Add `lp-color-border-ui-secondary` token
- Update `lp-color-shadow-ui-primary` token value to improve design
Improve theming support for table header and row borders
Improve theming support for TabList items
Switch to `lp-color-border-ui-secondary` border style
Switch to `lp-color-border-ui-secondary` border style
Explicitly specify a color for `close` kind buttons
Improve theming support for avatar component
=> fix: border/shadow token updates

.changeset/shy-jobs-cross.md, packages/drawer/src/styles/Drawer.module.css, packages/modal/src/styles/Modal.module.css, packages/navigation/src/styles/Navigation.module.css, packages/notification/src/styles/NotificationCenter.css, packages/popover/src/styles/Popover.module.css, packages/progress-bubbles/src/styles/ProgressBubbles.module.css, packages/snackbar/src/styles/SnackbarCenter.module.css, packages/split-button/src/styles/SplitButton.css, packages/table/src/styles/Table.module.css, packages/toast/src/styles/ToastCenter.module.css, packages/tokens/src/color.yaml, packages/tooltip/src/styles/Tooltip.module.css
Update z-index
Update z-index
Update primary bottom border color
Update z-index
Update z-index
Update z-index
Improve theming for button borders
Improve theming for table cell head
Update z-index
Update z-index
- Update `lp-color-bg-interactive-disabled` dark value
- Update `lp-color-bg-overlay-primary` dark value
- Update `lp-color-border-interactive-secondary` dark value
- Update `lp-color-border-interactive-disabled` dark value
=> fix: update darkmode values across system

packages/menu/stories/Menu.stories.tsx
Added some new stories to visualize some usecases/variants supported in LaunchPad
=> chore(menu): add menu stories

.changeset/witty-maps-give.md, packages/form/src/styles/Form.module.css, packages/form/stories/TextField.stories.tsx, packages/tokens/src/color.yaml
- Added `*-field-error` tokens to apply theming consistently across fields in an error state
=> feat(form,tokens): improve form theming

MIGRATION.md
We keep this doc up-to-date with latest migration notes between major/minor versions. It's gotten slightly out of date so this PR adds notes for the last few versions.
=> chore: update migration docs

.changeset/mighty-donkeys-cough.md, packages/button/src/styles/ButtonVariables.css, packages/form/src/styles/Form.module.css, packages/progress-bubbles/src/styles/ProgressBubbles.module.css, packages/tokens/src/color.yaml
Update theme tokens for dark mode button, form, and progress-bubbles
[Button]: Update destructive theme tokens
[Form]: Update placeholder and border colors
[ProgressBubbles]: Update backgrounds for dark mode
[Tokens]: Update tokens for related component changes
=> chore: update theme tokens for buttons, form, and progress bubbles

.changeset/lazy-hats-roll.md, packages/alert/src/styles/Alert.module.css, packages/alert/src/styles/CollapsibleAlert.module.css, packages/banner/src/styles/Banner.module.css, packages/button/src/styles/ButtonVariables.css, packages/tokens/src/color.yaml
Improve dark mode theming for alerts
=> feat(alert): enhance dark mode support for alerts

.changeset/dry-pumpkins-fetch.md, .github/workflows/changeset-check.yml, package.json, packages/progress-bubbles/src/utils.ts, pnpm-lock.yaml
Tested this locally by diffing the build and running in a consumer app to ensure the build still succeeds and runs.
=> chore: upgrade vite to 4.0

.changeset/wild-coats-cross.md, packages/banner/src/styles/Banner.module.css
Customize background color of banners in dark mode
=> chore(banner): update darkmode background styles

.changeset/smooth-sloths-perform.md, packages/popover/src/styles/Popover.module.css
Fixes a bug with the box shadow. Applied an invalid box shadow.
=> fix(popover): fix invalid box shadow property value

.changeset/three-news-camp.md, packages/menu/src/styles/Menu.css
=> fix(menu): update divider color

.changeset/nice-poets-deny.md, packages/icons/icons/arrow-down-thin.svg, packages/icons/icons/arrow-left-thin.svg, packages/icons/icons/arrow-right-thin.svg, packages/icons/icons/arrow-up-thin.svg
Adding arrow icons provided by design for the flag creation project
N/A
=> feat(icon): add arrow-<direction>-thin icons

.changeset/ten-frogs-behave.md, packages/alert/src/styles/Alert.module.css
=> fix(alert): fix white-space: nowrap bug in alert content

.changeset/strange-impalas-search.md, packages/tokens/src/color.yaml
Changes requested from Antonio.
=> fix(tokens): update theme tokens

.changeset/curly-buckets-rhyme.md, packages/icons/icons/arrow-drop-down.svg, packages/icons/icons/arrow-right.svg
Adding icons for the release path dashboard flag list view as requested by Antonio.
=> feat(icon): add arrow icons for release paths flag list view

.eslintrc.js, package.json, pnpm-lock.yaml
Update `eslint-plugin-functional` package and apply [breaking changes](https://github.com/eslint-functional/eslint-plugin-functional/blob/main/CHANGELOG.md#breaking-changes)
=> chore(deps): update eslint-plugin-functional package

.changeset/funny-trainers-repeat.md, packages/menu/package.json, packages/navigation/package.json, pnpm-lock.yaml
Updating React Router DOM to `6.7.0`.
=> chore: update to react-router-dom@6.7.0

.changeset/cyan-kids-explain.md, packages/drawer/src/styles/Drawer.module.css, packages/modal/src/styles/Modal.module.css
Design has asked the modal and drawer overlay backgrounds be updated.
=> fix(modal,drawer): update overlay bg colors

.changeset/grumpy-mice-nail.md, packages/navigation/src/styles/Navigation.module.css
Ensure that the `:active` styles are correct for secondary nav items
=> chore: update secondary navigation :active styles

.changeset/real-teachers-tickle.md, packages/chip/src/styles/Chip.module.css, packages/clipboard/src/styles/CopyCodeButton.module.css, packages/tokens/src/color-primitives.yaml
update default bg colors and add white 200 token
=> fix(chip): update default chip color

.changeset/brown-goats-check.md
=> fix: trigger release change

.changeset/sweet-terms-warn.md
=> fix: trigger-release 2

.changeset/purple-dancers-whisper.md, packages/tokens/sd.config.js
Related to incident where users are not seeing a default data theme.
=> fix: root styling issue

.changeset/many-kangaroos-cheer.md, pnpm-lock.yaml
=> ci: Update Lockfile

.changeset/large-flowers-judge.md, packages/chip/src/Chip.tsx, packages/chip/src/styles/Chip.module.css, packages/chip/stories/Chip.stories.tsx
Implement the error chip designed in Figma
=> feat(chip): add error chip

.changeset/tiny-laws-bathe.md, packages/popover/__tests__/Popover.spec.tsx, packages/popover/package.json, packages/popover/src/Popover.tsx, pnpm-lock.yaml
Reverts a change made here: https://github.com/launchdarkly/launchpad-ui/pull/809
=> fix(popover): remove ref merging logic

pnpm-lock.yaml
Reverts launchdarkly/launchpad-ui#808
=> chore(deps): revert lock file maintenance

.changeset/early-carpets-build.md, MIGRATION.md, packages/select/package.json, packages/select/src/__tests__/examples.tsx, packages/tag/__tests__/Tag.spec.tsx, packages/tag/package.json, packages/tag/src/Tag.tsx, packages/tag/src/TagGroup.tsx, packages/tag/src/types.ts, packages/tag/stories/Tag.stories.tsx, pnpm-lock.yaml
Update React Aria tag to the [latest stable release](https://react-spectrum.adobe.com/releases/2023-05-24.html#taggroup-api-update) and apply API changes.
=> chore(tag)!: update React Aria tag

.changeset/eight-bugs-rhyme.md, packages/modal/src/Modal.tsx, packages/modal/src/ModalContainer.tsx, packages/modal/src/styles/Modal.module.css, packages/modal/stories/Modal.stories.tsx, pnpm-lock.yaml
=> feat(modal)!: add and update sizes

.changeset/gold-dodos-prove.md, .github/workflows/chromatic.yml, packages/tokens/src/color-aliases.yaml, tsconfig.base.json
- Update `lp-color-text-ui-tertiary` to `gray-500`
- Update TS target to `es2021`
- Run Chromatic only on branch pushes and ignore tag pushes
=> fix(tokens): update text-ui-tertiary (dark) to gray-500

.storybook/preview.tsx, .storybook/styles.css, packages/avatar/stories/Avatar.stories.tsx, packages/clipboard/stories/CopyToClipboard.stories.tsx, packages/drawer/stories/Drawer.stories.tsx, packages/dropdown/stories/Dropdown.stories.tsx, packages/modal/stories/Modal.stories.tsx, packages/popover/stories/Popover.stories.tsx, packages/slider/stories/Slider.stories.tsx, packages/tokens/stories/z-index.stories.tsx, packages/tooltip/stories/Tooltip.stories.tsx
Ensure our side-by-side theme snapshots capture the full height of the page.
Chromatic snapshots capture full page height.
=> fix: update Storybook decorator to capture full page in Chromatic

.changeset/rotten-impalas-pretend.md, packages/icons/src/img/sprite.svg
Update the viewbox for grid-3x3 to match the version before the refactor.
=> fix(icons): update grid-3x3 viewbox

.github/workflows/chromatic.yml
Get the Chromatic token from aws ssm.
=> ci: get chromatic token from aws

nx.json
Address warnings by running `pnpm nx repair`.
=> chore: update nx config

.changeset/three-rice-wash.md, packages/menu/src/Menu.tsx, packages/menu/stories/Menu.stories.css, packages/menu/stories/Menu.stories.tsx, pnpm-lock.yaml
- When menu item is disabled, custom class names (`menuItemClassName`) were not being passed in, resulting in a mismatched menu item
- Added story with custom class name with disabled menu item
- manual
=> fix(menu): fix custom class names not getting applied to disabled menu items

.storybook/preview.tsx, package.json, playwright.config.ts, playwright/a11y.spec.ts, pnpm-lock.yaml
Wait for portals to be visible before running `axe` scans.
=> fix: wait for portals to be visible in a11y tests

.changeset/strong-turtles-attend.md, packages/alert/src/Alert.tsx
Use updated icon name in latest alert update.
=> fix(alert): update link icon

.changeset/wise-buckets-deliver.md, packages/menu/src/styles/Menu.css, packages/menu/stories/Menu.stories.css, packages/menu/stories/Menu.stories.tsx, packages/popover/src/styles/Popover.module.css
=> feat: refresh menu component

packages/tokens/package.json
To ensure a new version gets published.
=> fix: correct tokens alpha version

.changeset/warm-papayas-hear.md, packages/tokens/build.ts, packages/tokens/package.json, packages/tokens/src/color-aliases.yaml, pnpm-lock.yaml
Ensure keyword values are retained.
=> fix(tokens): keep css color keywords

.github/workflows/verify.yml, .storybook/Block.tsx, .storybook/utils.tsx, apps/remix/package.json, apps/remix/tsconfig.json, package.json, packages/banner/stories/Banner.stories.tsx, packages/chip/__tests__/Chip.spec.tsx, packages/clipboard/src/CopyToClipboard.tsx, packages/filter/src/AppliedFilterButton.tsx, packages/icons/stories/Icon.stories.tsx, packages/markdown/stories/Markdown.stories.tsx, packages/popover/src/Popover.tsx, packages/progress/__tests__/Progress.spec.tsx, packages/select/__tests__/examples.tsx, packages/tab-list/__tests__/TabList.spec.tsx, packages/tag/src/Tag.tsx, packages/tokens/stories/size.stories.tsx, packages/tokens/stories/tokens.stories.tsx, pnpm-lock.yaml, tsconfig.json, vite.config.ts
We've only been type checking source files being built for our packages. We should also type check our tests, stories, and other files outside the packages.
=> fix: type check all files

.changeset/swift-oranges-kneel.md, packages/tokens/src/typography.yaml, packages/tokens/stories/typography.stories.tsx
Use semibold instead of extrabold.
=> fix(tokens): update small to use semibold

package.json, packages/clipboard/stories/CopyToClipboard.stories.tsx, packages/inline-edit/stories/InlineEdit.stories.tsx, packages/menu/stories/Menu.stories.tsx, packages/modal/stories/Modal.stories.tsx, packages/popover/stories/Popover.stories.tsx, packages/snackbar/stories/SnackbarCenter.stories.tsx, packages/toast/stories/ToastCenter.stories.tsx, packages/tooltip/stories/Tooltip.stories.tsx, pnpm-lock.yaml, test/setup.ts
Per Storybook's recommendation.
=> chore: migrate to @storybook/test

.storybook/main.ts, package.json, packages/clipboard/stories/CopyToClipboard.stories.tsx, packages/inline-edit/stories/InlineEdit.stories.tsx, packages/menu/stories/Menu.stories.tsx, packages/modal/stories/Modal.stories.tsx, packages/popover/stories/Popover.stories.tsx, packages/snackbar/stories/SnackbarCenter.stories.tsx, packages/toast/stories/ToastCenter.stories.tsx, packages/tooltip/stories/Tooltip.stories.tsx, pnpm-lock.yaml
Undo `@storybook/test` update as it seems to be causing babel errors.
=> fix: chromatic builds

.changeset/two-geckos-whisper.md, .storybook/main.ts, apps/remix/app/data.server.ts, apps/remix/app/routes/rac.button.tsx, apps/remix/app/routes/rac.link-button.tsx, apps/remix/package.json, packages/components/__tests__/Button.spec.tsx, packages/components/__tests__/ButtonGroup.spec.tsx, packages/components/__tests__/IconButton.spec.tsx, packages/components/__tests__/LinkButton.spec.tsx, packages/components/package.json, packages/components/src/Button.tsx, packages/components/src/ButtonGroup.tsx, packages/components/src/IconButton.tsx, packages/components/src/LinkButton.tsx, packages/components/src/index.ts, packages/components/src/styles/Button.css.ts, packages/components/src/styles/ButtonGroup.css.ts, packages/components/src/styles/IconButton.css.ts, packages/components/stories/Button.stories.tsx, packages/components/stories/ButtonGroup.stories.tsx, packages/components/stories/IconButton.stories.tsx, packages/components/stories/LinkButton.stories.tsx, pnpm-lock.yaml, renovate.json
Add `Button`, `ButtonGroup`, `IconButton`, and `LinkButton` RAC-based components.
=> feat(components): add `Button`, `ButtonGroup`, `IconButton`, and `LinkButton`

.changeset/funny-shirts-jam.md, apps/remix/app/data.server.ts, apps/remix/app/routes/rac.popover.tsx, packages/components/__tests__/Popover.spec.tsx, packages/components/src/Dialog.tsx, packages/components/src/Heading.tsx, packages/components/src/Popover.tsx, packages/components/src/index.ts, packages/components/src/styles/Dialog.module.css, packages/components/src/styles/Popover.module.css, packages/components/src/styles/Tooltip.module.css, packages/components/stories/Popover.stories.tsx
Add `Popover` and its supporting components `Dialog`, `DialogTrigger`, `Heading`, and `OverlayArrow`.
=> feat(components): add `Dialog`, `DialogTrigger`, `Heading`, `OverlayArrow`, and `Popover`

.husky/commit-msg, .husky/pre-commit, package.json, playwright/a11y.spec.ts, pnpm-lock.yaml
Forgot to update the a11y tests after #1138 to run for each theme.
=> fix: run a11y tests on dark mode

.changeset/lazy-carpets-laugh.md, apps/remix/app/data.server.ts, apps/remix/app/routes/rac.switch.tsx, packages/components/__tests__/Switch.spec.tsx, packages/components/src/Button.tsx, packages/components/src/Dialog.tsx, packages/components/src/IconButton.tsx, packages/components/src/LinkButton.tsx, packages/components/src/Popover.tsx, packages/components/src/ProgressBar.tsx, packages/components/src/Switch.tsx, packages/components/src/Tooltip.tsx, packages/components/src/index.ts, packages/components/src/styles/Switch.module.css, packages/components/src/styles/Tooltip.module.css, packages/components/stories/Switch.stories.tsx
Add `Switch` and add JSDoc to components so folks can easily access RAC docs.
=> feat(components): add `Switch`

.changeset/fair-tools-fail.md
=> chore: publish all packages impacted by class pattern change

.changeset/hungry-dodos-explode.md, packages/components/src/styles/Menu.module.css, packages/components/src/styles/Popover.module.css, packages/components/src/styles/Switch.module.css, packages/components/stories/Menu.stories.tsx
Add story for items with icons and menu item states.
=> fix(components): align menu item contents

.github/workflows/changeset-check.yml, .github/workflows/chromatic.yml, .github/workflows/package-size.yml, .github/workflows/release.yml, .github/workflows/verify.yml, .storybook/main.ts, .storybook/preview-head.html, .storybook/preview.tsx, package.json, pnpm-lock.yaml, tsconfig.json
Ensure docs theme matches `prefers-color-scheme` and add mirror toggle in toolbar to mirror our themes.
https://github.com/launchdarkly/launchpad-ui/assets/2147624/51342e9b-78de-4a66-9095-c40014f5f02b
=> feat: match docs theme with ui and add mirror to toolbar for Storybook

.github/workflows/chromatic.yml, package.json, pnpm-lock.yaml
=> chore: update chromatic to v11

.changeset/chilled-bobcats-invent.md, package.json, packages/components/src/styles/Input.module.css, packages/components/src/styles/Tooltip.module.css, packages/components/stories/ListBox.stories.tsx, packages/components/stories/Menu.stories.tsx, packages/components/stories/Modal.stories.tsx, packages/components/stories/Popover.stories.tsx, packages/components/stories/RadioGroup.stories.tsx, packages/components/stories/Select.stories.tsx, packages/components/stories/TagGroup.stories.tsx, packages/components/stories/Tooltip.stories.tsx, pnpm-lock.yaml
Adjust padding on `Tooltip` and `Input`. Also add `subcomponents` to stories since SB v8 supports it.
=> fix(components): adjust padding on `Tooltip` and `Input`

.changeset/witty-moles-brush.md, biome.json, packages/table/src/TableCell.tsx
Revert change from Biome lint for deleting a prop as it wasn't removed properly.
=> fix(table): prop deletion

.changeset/lucky-olives-heal.md, packages/components/__tests__/TagGroup.spec.tsx, packages/components/src/TagGroup.tsx
Include `Tag` textValue in remove label to distinguish them.
=> fix(components): include `Tag` textValue in remove label

.changeset/cuddly-moles-carry.md, .storybook/preview.tsx, packages/components/src/ComboBox.tsx, packages/components/src/index.ts, packages/components/src/styles/ComboBox.module.css, packages/components/src/styles/Popover.module.css, packages/components/stories/ComboBox.stories.tsx, packages/components/stories/composition.stories.tsx
Add `ComboBoxClearButton` and recipe stories.
=> feat(components): add `ComboBoxClearButton`

.changeset/swift-gifts-double.md, packages/components/src/styles/IconButton.module.css
Prevent icon button shrinking.
=> fix(components): prevent icon button shrinking

.changeset/little-birds-divide.md, packages/components/src/Section.tsx, packages/components/src/Separator.tsx, packages/components/src/styles/ListBox.module.css, packages/components/src/styles/Menu.module.css, packages/components/src/styles/Popover.module.css, packages/components/src/styles/Section.module.css, packages/components/src/styles/Separator.module.css, packages/components/stories/Menu.stories.tsx
Update to match latest designs.
=> fix(components): update menu styles

.changeset/polite-zebras-prove.md, packages/components/src/Header.tsx, packages/components/src/styles/Header.module.css, packages/components/src/styles/Menu.module.css, packages/components/src/styles/Popover.module.css
Extract `Header` styles out from `Menu`.
=> fix(components): extract `Header` styles

.changeset/mighty-donuts-talk.md, packages/components/src/styles/Input.module.css
Update padding to result in a height of 32.
=> fix(components): adjust `Input` padding

packages/icons/CHANGELOG.md
=> docs: update icons changelog

.changeset/slow-camels-live.md, packages/components/src/styles/Popover.module.css, stylelint.config.js
Set overflow on non-menu popovers.
=> fix(components): set overflow on non-menu popovers

.changeset/sweet-planets-mate.md, packages/components/src/styles/Popover.module.css
=> fix(components): remove border from `Popover`

.changeset/chilly-panthers-pay.md, packages/components/src/styles/FieldGroup.module.css, packages/components/src/styles/Radio.module.css
=> fix(components): increase `Radio` icon specificity

.changeset/perfect-clouds-nail.md, packages/components/src/styles/Popover.module.css
Adjust padding and add a min width.
=> fix(components): update `Popover` styles

.changeset/bright-ghosts-admire.md, packages/components/__tests__/ToggleButton.spec.tsx, packages/components/src/ButtonGroup.tsx, packages/components/src/IconButton.tsx, packages/components/src/LinkIconButton.tsx, packages/components/src/RadioIconButton.tsx, packages/components/src/ToggleButton.tsx, packages/components/src/ToggleIconButton.tsx, packages/components/src/index.ts, packages/components/stories/ToggleButton.stories.tsx, packages/components/stories/ToggleIconButton.stories.tsx
=> feat(components): add `ToggleButton`

.changeset/khaki-pets-perform.md, packages/components/src/styles/Button.module.css, packages/components/src/styles/Checkbox.module.css, packages/components/src/styles/Group.module.css, packages/components/src/styles/Link.module.css, packages/components/src/styles/Radio.module.css, packages/components/src/styles/Switch.module.css, packages/components/src/styles/TagGroup.module.css
Inset focus outlines to avoid issues with overflow settings on containers cutting them off.
=> refactor(components): inset focus outlines

.changeset/large-bugs-flow.md, packages/components/src/TagGroup.tsx, packages/components/src/styles/TagGroup.module.css, packages/components/stories/TagGroup.stories.tsx
=> feat(components): add `info` variant for `Tag`

.changeset/fresh-cows-draw.md, packages/components/src/Modal.tsx, packages/components/src/styles/Modal.module.css
=> feat(components): add `large` size for `Modal`

.changeset/plenty-ants-study.md, packages/components/src/styles/Checkbox.module.css
Adjust `Checkbox` border-radius.
=> fix(components): adjust `Checkbox` border-radius

.changeset/plenty-bikes-hide.md, packages/components/src/ListBox.tsx, packages/components/src/Menu.tsx, packages/components/src/styles/ListBox.module.css, packages/components/src/styles/Menu.module.css, packages/components/src/styles/Select.module.css, packages/components/stories/ListBox.stories.tsx
Refactor `ListBoxItem` and `MenuItem` styles to be less complex and ensure parity between the two. Add missing stories to `ListBox` that resulted in a regression.
Chromatic shows no regressions.
=> fix(components): refactor `ListBoxItem` and `MenuItem` styles

.changeset/tasty-coins-nail.md, packages/card/src/RadioCard.tsx, packages/card/stories/RadioCard.stories.tsx, packages/clipboard/src/CopyToClipboard.tsx, packages/clipboard/stories/CopyToClipboard.stories.tsx, packages/snackbar/src/Snackbar.tsx, packages/snackbar/src/SnackbarCenter.tsx, packages/snackbar/stories/Snackbar.stories.tsx, packages/snackbar/stories/SnackbarCenter.stories.tsx, packages/toast/src/Toast.tsx, packages/toast/src/ToastCenter.tsx, packages/toast/stories/Toast.stories.tsx, packages/toast/stories/ToastCenter.stories.tsx
Deprecate packages that have a RAC replacement.
=> chore: deprecate packages

docs/tech-stack.md, packages/core/stories/getting-started.mdx, packages/tokens/tsconfig.json
Fix TS not resolving LP pkg references in the tokens story files locally.
=> fix(icons): include pkg ts paths

.changeset/beige-spoons-smoke.md, .storybook/main.ts, packages/components/__tests__/Calendar.spec.tsx, packages/components/__tests__/DateField.spec.tsx, packages/components/__tests__/DatePicker.spec.tsx, packages/components/package.json, packages/components/src/Calendar.tsx, packages/components/src/DateField.tsx, packages/components/src/DatePicker.tsx, packages/components/src/FieldGroup.tsx, packages/components/src/index.ts, packages/components/src/styles/Calendar.module.css, packages/components/src/styles/DateField.module.css, packages/components/src/styles/DatePicker.module.css, packages/components/src/styles/Group.module.css, packages/components/src/styles/Input.module.css, packages/components/src/styles/Popover.module.css, packages/components/stories/Calendar.stories.tsx, packages/components/stories/DateField.stories.tsx, packages/components/stories/DatePicker.stories.tsx, packages/components/stories/DateRangePicker.stories.tsx, packages/components/stories/RangeCalendar.stories.tsx, packages/components/stories/TimeField.stories.tsx, pnpm-lock.yaml
Add `Calendar`, `DateField`, `DatePicker`, `DateRangePicker`, `RangeCalendar`, and `TimeField`. To follow up with [preset dates functionality](https://react-spectrum.adobe.com/react-aria/Calendar.html#contexts).
Check stories in `Date and Time` section.
=> feat(components): add `Calendar`, `DateField`, `DatePicker`, `DateRangePicker`, `RangeCalendar`, and `TimeField`

.changeset/strange-humans-sleep.md, packages/components/__tests__/Dialog.spec.tsx, packages/components/src/Dialog.tsx, packages/components/src/styles/Modal.module.css, packages/components/stories/Modal.stories.tsx
Add `subtitle` slot to `Dialog` that describes modals.
=> feat(components): add `subtitle` slot to `Dialog`

.changeset/selfish-hotels-jog.md, packages/tokens/src/color-aliases.json
We are adding color tokens for the revamping of the Snippet component.
=> feat(tokens): add code color aliases tokens

packages/tokens/build.ts, packages/tokens/package.json, pnpm-lock.yaml
Bump style-dictionary to stable release.
=> chore: bump style-dictionary to stable release
