launchdarkly/launchpad-ui

- .github/workflows/chromatic.yml
- packages/tokens/src/color.yaml
Both icons and tokens are transformed (processed externally) outside of Vite and so we need to set the [externals](https://www.chromatic.com/docs/turbosnap#specify-external-files-to-trigger-a-full-re-test-when-they-change) option for Chromatic to a picomatch glob to match those files. This updates it to include the token yaml files and ensure snapshots are compared.
> ci: update TurboSnap externals to include token changes

- .changeset/twenty-jobs-allow.md
- packages/alert/src/styles/CollapsibleAlert.module.css
- packages/button/src/styles/ButtonGroup.css
- packages/button/src/styles/ButtonVariables.css
- packages/chip/src/styles/Chip.module.css
- packages/clipboard/src/styles/CopyCodeButton.module.css
- packages/filter/src/styles/Filter.module.css
- packages/form/src/styles/Form.module.css
- packages/menu/src/styles/Menu.css
- packages/modal/src/styles/Modal.module.css
- packages/notification/src/styles/Notification.css
- packages/popover/src/styles/Popover.module.css
- packages/slider/src/styles/Slider.module.css
- packages/tokens/src/border.yaml
- packages/tokens/src/color.yaml
Update theme tokens and usage in LaunchPad
- Add `lp-color-shadow-ui-primary`
- Add a dark theme value to `lp-color-border-ui-primary`
- Rename `lp-border-radius` to `lp-border-radius-regular` and add `lp-border-radius-medium`
Rename `lp-border-radius` to `lp-border-radius-regular`
Rename `lp-border-radius` to `lp-border-radius-regular`
Rename `lp-border-radius` to `lp-border-radius-regular`
Rename `lp-border-radius` to `lp-border-radius-regular`
Rename `lp-border-radius` to `lp-border-radius-regular`
Rename `lp-border-radius` to `lp-border-radius-regular`
Rename `lp-border-radius` to `lp-border-radius-regular`
Support theming in `CopyCodeButton`
- Rename `lp-border-radius` to `lp-border-radius-regular`
- Support theming in filter button and applied filter button components
Support …
> fix: update darkmode values across system

- .changeset/afraid-bananas-wait.md
- packages/filter/src/styles/Filter.module.css
This style is actually causing a visual bug in our core app:
> fix(filter): remove filter target style

- .changeset/loud-dolphins-retire.md
- packages/form/src/styles/Form.module.css
- packages/form/stories/TextArea.stories.tsx
- packages/form/stories/TextField.stories.tsx
- packages/tokens/src/color.yaml
- Adds new `-field-` variant tokens. Previously, we were using the `interactive` variant, which is also used by buttons and focusable elements, but for the case of fields, we can be more explicit and granular so styling can be safely applied to only fields, and in consumer applications we can confidently use these tokens when styling forms.
> refactor(form,tokens): improve theming with new field tokens

- .changeset/quiet-cheetahs-laugh.md
- packages/button/src/styles/ButtonVariables.css
This PR improves button styles in LaunchPad for destructive buttons in dark mode
Before:
After:
> refactor(button): update button destructive styles

- .changeset/tricky-horses-hope.md
- packages/button/src/styles/ButtonVariables.css
- packages/tokens/src/color.yaml
After meeting with the design team, we decided to implement the following changes:
- Destructive buttons in dark mode should have no background color in their default state
- Tweak Gray 600 and Red 600 to comply with contrast ratio criteria
- Update interactive secondary border color to increase contrast
- Update link color in darkmode from Cyan 600 to 500.
> chore(tokens,button): update tokens based on design feedback

- .changeset/spicy-llamas-dream.md
- packages/navigation/__tests__/LegacyNavigation.cy.tsx
- packages/navigation/__tests__/LegacyNavigation.spec.tsx
- packages/navigation/src/index.ts
- packages/navigation/src/legacy/Nav.tsx
- packages/navigation/src/legacy/NavItem.tsx
- packages/navigation/src/legacy/NavItemWithTooltip.tsx
- packages/navigation/src/legacy/Navigation.tsx
- packages/navigation/src/legacy/NavigationContext.ts
- packages/navigation/src/legacy/NavigationItem.tsx
- packages/navigation/src/legacy/NavigationList.tsx
- packages/navigation/src/legacy/NavigationMenuDropdown.tsx
- packages/navigation/src/legacy/styles/Navigation.module.css
- packages/navigation/src/legacy/utils.ts
Adding back the legacy versions of `<Navigation />` that were changed in https://github.com/launchdarkly/launchpad-ui/pull/603
> feat: add legacy Navigation components

- .changeset/big-geckos-draw.md
- packages/banner/__tests__/Banner.cy.tsx
- packages/banner/__tests__/Banner.spec.tsx
- packages/banner/src/Banner.tsx
Fix bugs where `dismissible` props were passed to the banner component without an `onDismiss` function. This results in the banner _not_ being dismissed when clicked.
> refactor(banner): remove dismissible prop in favor of onDismiss prop

- .changeset/silver-spiders-itch.md
- packages/alert/src/styles/Alert.module.css
Adds break-word property to alert content to avoid content flowing outside alert container by default.
> fix(alert): add break-word property to alert content

- .changeset/four-cups-poke.md
- packages/drawer/src/styles/Drawer.module.css
- packages/modal/src/styles/Modal.module.css
- packages/popover/src/styles/Popover.module.css
- packages/snackbar/src/styles/SnackbarCenter.module.css
- packages/toast/src/styles/ToastCenter.module.css
- packages/tooltip/src/styles/Tooltip.module.css
Currently, we have z-index levels 100 through 900. LaunchPad occupies 300 through 700. In our main app, this only leaves levels 100 and 200 for app-level z-indexing. This isn't enough, since we have three levels of z-indexing that need to be considered. Since we technically still have levels 800 and 900 unassigned, the solution presented in this PR is to bump all z-indexes in LaunchPad by +100, so that we have 1 extra z-index level available in the consumer app levels.
Here is the impetus for this fix (where both the banner container and the app sidebar use z-index-100, and neither should be bumped to 200 since topbar currently occupies that value):
> fix: bump z-index values across design system

- .changeset/pretty-schools-study.md
Tacking this on after realizing the https://github.com/launchdarkly/launchpad-ui/pull/673 incorrectly marked `core` and `filter` as patch updates (instead of minor updates to match `menu` and `navigation`).
> chore: minor bump in core and filter after updating to react-router-dom@6.7.0

- .changeset/curly-ligers-yawn.md
- packages/clipboard/src/CopyCodeButton.tsx
The default copy button's `type` attribute defaults to `submit`, which potentially triggers unwanted form submissions.
> fix(copy-to-clipboard): add button type to default copy button

- .changeset/long-goats-sleep.md
- packages/form/src/FormField.tsx
- packages/form/stories/FormGroup.stories.tsx
- packages/form/stories/Label.stories.tsx
- packages/form/stories/TextField.stories.tsx
- Use LaunchPad `Label` component in `FormField` component. Design asked us why some labels were being rendered at 16px font size, and it was because we were using `FormField` in some places, and this was using a browser native `label` element and not receiving the correct font size.
- Improve Form stories to more properly convey what the scope of each Form component actually is.
> fix(form): update form stories and make FormField use Label component

- .changeset/poor-cooks-sniff.md
- packages/drawer/__tests__/Drawer.spec.tsx
- packages/drawer/src/Drawer.tsx
In the New Flag Creation Experience I had to add this CSS hack to make the cancel icon go away in Drawer:
```
.entity-creation__drawer > div > div > .IconButton {
display: none;
}
```
We did this because this Drawer had several bits of custom UI for breaking out of it, and the icon was occupying space in the header of the drawer.
To avoid doing such hacks in the future, Squonk wanted to add a toggle to the `Drawer`. It's a boolean flag that controls whether the `IconButton` appears in the DOM or not.
Added unit test coverage.
> feat(drawer): add cancel icon toggle to Drawer

- .changeset/chilly-rice-doubt.md
- packages/drawer/package.json
- packages/modal/package.json
- packages/popover/package.json
- packages/snackbar/package.json
- packages/toast/package.json
- pnpm-lock.yaml
Followed along with the [upgrade guide for framer-motion](https://www.framer.com/motion/guide-upgrade/) to determine that we can safely update framer-motion to 9.0.3 from 7.6.1. Let's release this as a standalone version upgrade to LaunchPad so if something does pop up in Gonfalon, we can revert this in isolation. Gonfalon _also_ imports `framer-motion`, and I tested there that upgrading to 9.0.3 does not result in any test failures.
> chore(deps): update framer motion from 7.6.1 to 9.0.3

- .changeset/rich-ways-remember.md
- .github/workflows/chromatic.yml
- packages/button/src/Button.tsx
- packages/button/src/styles/Button.css
- packages/button/src/styles/ButtonVariables.css
- packages/button/stories/Button.stories.tsx
- packages/split-button/src/styles/SplitButton.css
I updated the button styles to match Figma.
I just tested visually.
One thing to note is that I _think_ Launchpad isn't loading Inter, which makes developing in Launchpad tough since the font will always be different. I installed Inter locally while making these changes which I think fixed it, but it's hard for me to know for sure since Inter and the fallback font (apple system font? SF Pro?) are pretty similar. So if we could Inter in Storybook while developing it would help us stay closer to how everything is styled in gonfalon.
> fix: update button styles to match Figma

- .changeset/soft-boxes-know.md
The "language" icon svg was added in a previous PR, but the corresponding `Language` icon component was not generated with it. This PR adds the component for the now-available icon.
> feat(icons): add language icon component

- .changeset/selfish-bananas-leave.md
- packages/select/src/MultiSelect/MultiSelect.tsx
- packages/select/src/MultiSelect/useMultiSelect.ts
- packages/select/src/SingleSelect/SingleSelect.tsx
- packages/select/src/SingleSelect/useSingleSelect.ts
- packages/select/src/styles/Select.module.css
- packages/select/src/types.ts
Renaming the `isDisabled` prop to `disabled` for `SingleSelect` and `MultiSelect`, so that it's more inline with consumer / native HTML expectations. `react-aria` expects `isDisabled` for its internal hooks. 
I also added styles that were missing for disabled comboboxes.
disabled combobox in light mode
disabled combobox in light mode
> feat(select): rename disabled prop and add styles

- .changeset/neat-boxes-fail.md
- packages/clipboard/src/styles/CopyCodeButton.module.css
Left-align the `CopyToClipboard` button text. In most cases this produces no visual difference, but it helps for the cases where longer text values are supplied and the content wraps to multiple lines.
**Before**:
**After**:
> feat: left-align CopyToClipboard text

- .changeset/tough-birds-agree.md
- packages/select/src/MultiSelect/MultiSelect.tsx
- packages/select/src/SelectItem.tsx
- packages/select/src/SelectListBox.tsx
- packages/select/src/SelectSection.tsx
- packages/select/src/SingleSelect/SingleSelect.tsx
- packages/select/src/__tests__/MultiSelect.cy.tsx
- packages/select/src/__tests__/MultiSelect.spec.tsx
- packages/select/src/__tests__/SingleSelect.cy.tsx
- packages/select/src/__tests__/SingleSelect.spec.tsx
- packages/select/src/index.ts
- packages/select/src/styles/Select.module.css
- packages/select/stories/MultiSelect.stories.tsx
- packages/select/stories/SingleSelect.stories.tsx
Based on some conversation with the team, we decided not to require consumers to use `react-stately`s `Item` and `Section` components directly, and instead expose named components through LaunchPad. These components in this case are `SelectItem` and `SelectSection`. 
I also added the `as` prop to `SelectItem`, which allows us to render selected items as links if needed, like in the case of the refactored Navigation component in this PR: https://github.com/launchdarkly/launchpad-ui/pull/696/files#diff-622d77675b453717536c6747bff490028f4b3ab94fd52c74f38dec365d91c1ffR23
> refactor(select): expose SelectItem and SelectSection

- .changeset/curly-shrimps-breathe.md
- packages/chip/src/Chip.tsx
- packages/chip/src/styles/Chip.module.css
- packages/chip/stories/Chip.stories.tsx
I noticed the LaunchDarkly app doesn't use the large variant chip, so we can deprecate it. With this change, the `size` prop is now irrelevant as well.
> chore(chip): remove large variant and size prop

- .changeset/afraid-penguins-change.md
- packages/chip/src/Chip.tsx
- packages/chip/src/styles/Chip.module.css
- packages/chip/stories/Chip.stories.tsx
Adds new size variants:
- `small`: 20px height
- `normal`: 28px height
- `legacy`: 24px height (**this is the legacy size, we should not use moving forward after we feature flag migrate the sizing change**)
Also removes interactive styling since we do not want to encourage making chips interactive.
> feat(chip): add size variants and deprecate unused variants

- .changeset/rude-carpets-jump.md
- packages/snackbar/src/styles/SnackbarCenter.module.css
- packages/toast/src/styles/ToastCenter.module.css
- packages/tooltip/src/styles/Tooltip.module.css
> fix: update tooltip, snackbar, and toast z-index

- .changeset/happy-nails-love.md
- packages/chip/src/Chip.tsx
- packages/chip/src/styles/Chip.module.css
- packages/chip/stories/Chip.stories.tsx
- Deprecate `label` variant
- Remove `legacy` variant, design decided to reduce padding back to 24px total height, making legacy unnecessary.
- Deprecate `subtle` variants
- Update normal and small sizing
> feat(chip): Update sizing, deprecate `kind=label` and `size=legacy` and `subtle`

- .changeset/fast-carrots-rhyme.md
- packages/tokens/sd.config.js
This was actually causing issues with the ability to nest themes, so I figured out a way to support data-theme in the Chromatic build of the main LD app. Now we can remove this.
> feat(tokens): remove root from token variables

- .changeset/beige-suits-remain.md
- packages/navigation/src/NavItem.tsx
I noticed that the Chip clips a bit when inside a NavItem. Changing the size to small for the Chip fixes the issue
Before:
After:
> fix(chip): adjust chip size in navitem to prevent clipping

- .changeset/giant-parents-poke.md
- packages/button/src/IconButton.tsx
- packages/button/stories/IconButton.stories.tsx
Controls the icon size based on the button size within IconButton, so that we have consistency across IconButtons for which icon size is used.
> fix(button): improve IconButton icon sizing

- .changeset/smart-rockets-attack.md
- packages/tab-list/src/styles/TabList.module.css
A few weeks ago, @kwatkins-ld and I removed the background color of the Navigation component so that it is more unopinionated about the background color of parent elements. Looking at the TabList in darkmode, it appears we should do the same thing.
> fix(tab-list): remove bg color

- renovate.json
We have several packages set to pinned dependency versions, and it makes sense to update these manually where possible instead of having renovate bot suggest we update them. These versions are also matched to ones in the downstream consumer app to minimize bundle size.
> chore: update renovate to only update range deps

- .changeset/rare-moles-trade.md
- packages/button/src/Button.tsx
- packages/button/src/IconButton.tsx
- packages/button/src/styles/Button.css
- packages/split-button/src/context.ts
- packages/split-button/src/styles/SplitButton.css
- packages/split-button/stories/SplitButton.stories.tsx
Renames `normal` to `medium` to go with the other t-shirt sizing values.
Improves button sizing so that IconButton and Button share the exact same heights for `small` and `medium` sizes. This makes putting them alongside one another look much more visually correct
Also refactors the SplitButton to remove unused css variables and improve naming for those that are there.
> feat(button): update button sizes

- .changeset/moody-gifts-lay.md
- packages/button/src/styles/Button.css
- packages/modal/src/ModalHeader.tsx
- packages/pagination/src/PaginationButton.tsx
We recently had a contribution spec approved to switch from round IconButtons to border-radius: 0.6rem. This aligns better with buttons so that they can sit next to eachother.
> refactor(button): switch from circular IconButton to rounded

- .changeset/thick-dots-change.md
- packages/alert/package.json
- packages/alert/src/Alert.tsx
- packages/alert/stories/Alert.stories.tsx
- pnpm-lock.yaml
One of our team members has requested that they have the ability to show/hide Alerts from the consumer. This change implements a controlled/uncontrolled state management solution using `react-stately`'s `useControlledState` hook, which is in use elsewhere across the design system.
> feat(alert): support uncontrolled handling of the dismiss prop

- .changeset/unlucky-shirts-sit.md
- apps/remix/app/routes/components/form.tsx
- packages/form/__tests__/Form.cy.tsx
- packages/form/src/FieldError.tsx
- packages/form/src/styles/Form.module.css
- packages/form/stories/FormField.stories.tsx
> feat(form): replace error text with icon

- .github/CODEOWNERS
Use the frontend team within the core group as codeowners since the current codeowner group is far too broad.
N/A
> Update CODEOWNERS to be frontend only

- .changeset/plenty-insects-sing.md
- packages/toggle/__tests__/Toggle.cy.tsx
- packages/toggle/__tests__/Toggle.spec.tsx
- packages/toggle/package.json
- packages/toggle/src/Toggle.tsx
- packages/toggle/src/styles/Toggle.module.css
- packages/toggle/stories/Toggle.stories.tsx
- pnpm-lock.yaml
- Rework toggle to rely more on the `react-aria`/`react-stately` hooks under the hood, similar to React Spectrum's implementation.
- Support controlled _or_ uncontrolled behavior, and show this in stories
- Remove label text props, since these are not used in our app
- Rename CSS variables to `--lp-component-*` syntax that's used elsewhere
> fix(toggle): rework toggle to use label around component

- .changeset/unlucky-ears-bake.md
- packages/tag/src/styles/Tag.module.css
To test: look at chromatic storybook build (will link once it's ready)
- Look at darkmode for link styles and removable styles
- Align remove button with IconButton styles (no longer circular)
> feat(tags): improve darkmode styles and IconButton style

- .changeset/two-jobs-retire.md
- packages/icons/__tests__/Icon.spec.tsx
- packages/icons/src/Icon.tsx
- packages/snackbar/src/styles/Snackbar.module.css
- packages/snackbar/stories/Snackbar.stories.tsx
…issue for snackbars
- Add `word-break` property to snackbar to avoid text that overflows outside of parent bounds
- Refactor icon props so that they get passed down to the svg itself instead of being applied to the span. This makes our icons more accessible since aria properties will be applied to the svg instead of a span.
- Move Header variant of snackbar to its own story
> fix(icons,snackbar): improve aria-labeling for icons, fix word-break issue for snackbars

- .changeset/mean-pandas-shake.md
- packages/button/src/styles/Button.css
- packages/tokens/src/color-aliases.yaml
The disabled state of the minimal button variant doesn’t look very inactive. I’m proposing we make the text color a lighter gray (gray-500 in default mode, gray-700 in dark mode) so it more clearly looks disabled.
To do this, I updated the `--lp-color-text-interactive-disabled` variable. This also updates the disabled style for text links, and disabled tabs list. In both situations, I think it's appropriate that these are updated and all match.
More detail here: https://launchdarkly.atlassian.net/wiki/spaces/ENG/pages/2392949075/Minimal+button+disabled+state
Last button is the disabled one.
Last button is the disabled one.
Last two tabs are disabled, and they actually look _more_ interactive than the interactive tab (second one).
Last two tabs are disabled, and they now look less …
> feat: update interactive disabled text color

- .changeset/strange-dancers-count.md
- packages/popover/__tests__/Popover.spec.tsx
- packages/popover/package.json
- packages/popover/src/Popover.tsx
- pnpm-lock.yaml
The `Popover` component was not merging user-supplied `ref`s with its own internal ref for the popover target element. That means that attaching a ref to the element/component supplied as the popover target would not take effect. Updating this is necessary for our a11y audit, as sometimes we need to manually refocus a popover target from the outside.
Added a unit test for this case.
> fix(popover): merge target refs

- .changeset/big-toys-eat.md
- packages/button/src/Button.tsx
The `<button>` element in HTML has a `type` prop, with a value of either "submit", "reset", or "button".
The `<a>` element, though, doesn't have a similar prop.
For better or worse, we're currently using the `<Button>` component to render both _things-that-look-like-buttons-but-are-really-links_ and _things-that-look-like-buttons-and-that-are-actually-buttons_. Our current `Button` component defaults to using `type="button"` for both kinds of elements, even when we intend for the final rendered component to be an `<a>` element.
Here's a button-looking-element that should be a **button** under the hood:
Here's a **link** that uses the same component for visual styling:
You can see that both have a `type` prop, but we only actually want that one on the `button`.
We get the `<a>` element by …
> fix(button): don't include the type prop when asChild is true

- .changeset/young-trains-help.md
- packages/filter/src/Filter.tsx
- packages/filter/src/FilterButton.tsx
This adds the ability to mark the button as disabled when appropriate and prevent the dropdown from opening when it is so. Currently, the filter button cannot be recognized as inactive by screen readers but this remedies that issue.
> feat(filter): add disabled prop to disable Filter

- .changeset/spicy-toes-study.md
- packages/filter/src/AppliedFilter.tsx
- packages/filter/src/Filter.tsx
- packages/filter/src/FilterMenu.tsx
- packages/menu/src/MenuSearch.tsx
This adds a prop, `searchId` to the Filter component to allow an external label to be used for accessibility.
> feat(filter): add searchId to associate labels with filter search

- .changeset/silent-nails-brake.md
- packages/drawer/package.json
- packages/drawer/src/Drawer.tsx
- packages/modal/package.json
- packages/modal/src/ModalContainer.tsx
- pnpm-lock.yaml
**Drawers**
The focus trap in all drawers is currently broken - you can tab out into the browser.
The fix for this was to render the portal separately from the drawer, in the same fashion as the modal component. The cause is still not 100% clear, but is likely due to some combination of context or re-rendering issues.
**Drawer + Modal combo** 
When a modal is triggered from a button inside a drawer, the event handlers become funky as both components are listening for the same Escape key event.
The fix: add/remove the event listeners based on if focus is within the drawer or modal.
**Screen reader accessibility for drawers and modals**
Changed aria-labelledby to aria-describedby so screen readers can properly announce the modal title
> fix: support modal + drawer combo; fix drawer focus trap

- .changeset/chilly-eggs-listen.md
- packages/menu/__tests__/Menu.spec.tsx
- packages/menu/package.json
- packages/menu/src/Menu.tsx
- packages/menu/src/MenuItem.tsx
- packages/menu/src/index.ts
- packages/menu/src/styles/Menu.css
- pnpm-lock.yaml
We have feature flagged this change for the last 2 months in the LaunchDarkly application, and confirmed that the router-agnostic method of using `asChild` works as expected.
> feat(menu): deprecate menuitemlink in favor of asChild

- .changeset/pretty-ducks-cheer.md
- packages/snackbar/src/styles/SnackbarCenter.module.css
The toast notification was over the drawer panel
BEFORE
AFTER
> Fix z-index for toast notification

- .changeset/quiet-gorillas-applaud.md
- packages/menu/__tests__/Menu.spec.tsx
- packages/menu/src/Menu.tsx
Items were getting clipped when virtualized such as when adding a profile picture or other element in the menu item. This will allows to have dynamic items.
> fix(menu): Allow different size shaped menu items when virtual

- .changeset/sour-panthers-build.md
- packages/clipboard/src/styles/CopyCodeButton.module.css
The Clipboard component has been updated to use the standard height used by the other button, `24px`
Before:
After:
> feat(clipboard): Update component height to match other button heights

- .changeset/heavy-berries-grab.md
- packages/form/src/SelectField.tsx
Adds ref forwarding to the `SelectField` component so it can be used with e.g. react-hook-forms.
No functional changes to test ^_^
I'm happy to add a unit test if you like, but I feel like that would just be testing React 😅
> fix: selectField ref forwarding

- packages/core/package.json
I have noticed that renovate bot isn't able to [pull in release notes when opening update PRs](https://github.com/launchdarkly/accelerate/pull/1815) for the `@launchpad/core` package.
After [doing some research](https://github.com/renovatebot/renovate/issues/4724#issuecomment-543171930), I'm hoping that adding this [info to the package.json](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#repository) will help.
> chore: add repo info to core package.json

- .changeset/pink-tips-draw.md
- packages/avatar/src/Avatar.tsx
The `Avatar` component doesn't expose error-handling to consumers, so it seems better to intentionally swallow errors from `fetch( ... )`.
> feat: suppress errors in Avatar when fetching image

- .github/workflows/release.yml
Use a custom GH token to allow CI checks to run on PRs opened by Changesets as seen in #882.
> ci: use GitHub PAT for changesets action

- .github/workflows/changeset-check.yml
- .github/workflows/verify.yml
Update our CI checks so that we can set them as required checks:
- Update `verify` to run on `main` so that Cypress cache persists across branch builds so that the check doesn't fail inconsistently
- Update `changeset-check` to run on all pull requests but succeed for Changeset release PRs and ones with the `skip changeset` label added
> ci: update checks to make them required

- .storybook/preview.tsx
- .storybook/styles.css
- packages/clipboard/stories/CopyToClipboard.stories.tsx
- packages/dropdown/stories/Dropdown.stories.tsx
- packages/icons/stories/Icon.stories.tsx
- packages/modal/stories/Modal.stories.tsx
- packages/popover/stories/Popover.stories.tsx
- packages/snackbar/stories/SnackbarCenter.stories.tsx
- packages/toast/stories/ToastCenter.stories.tsx
- packages/tooltip/stories/Tooltip.stories.tsx
Add a `side-by-side` option in our Storybook theme toggle and enable it during Chromatic builds so we can catch any dark mode issues/regressions.
> feat: add side-by-side theme in Storybook for snapshots

- .changeset/smooth-masks-end.md
- packages/markdown/src/utils.ts
Meant to systemically address CSS injections via Markdown component: https://app.shortcut.com/launchdarkly/story/207785/css-injection-on-segments#activity-208280
Forbidding style tags prevents malicious users from injecting style tags into user input that loads potentially malicious stylesheets from user-controlled sources (e.g., https://evil.com/style.css). CSS injection resources: https://owasp.org/www-project-web-security-testing-guide/v41/4-Web_Application_Security_Testing/11-Client_Side_Testing/05-Testing_for_CSS_Injection
Additionally, setting a base config for ALLOWED_TAGS gives us a base level configuration for when engineers forget to specify the allowedTags prop with the Markdown components, which has been a source of repeated HackerOne findings in the past. These tags should …
> fix: prevent css injection by forbidding style tags in Markdown component + adding base allowed tags

- .changeset/small-flowers-sin.md
- .gitignore
- docs/adr-005-styles.md
- docs/adr-006-scoped-styles.md
- package.json
- packages/tokens/README.md
- packages/tokens/package.json
- packages/tokens/sd.config.js
- packages/tokens/stories/tokens.stories.tsx
- packages/vars/README.md
- packages/vars/package.json
- packages/vars/src/index.ts
- packages/vars/src/vars.css.ts
- packages/vars/stories/Story.css.ts
- packages/vars/stories/vars.stories.tsx
- packages/vars/tsconfig.build.json
- pnpm-lock.yaml
- tsconfig.json
- vite.config.ts
- Add `vars` package to allow [Vanilla Extract](https://vanilla-extract.style/) users to consume our tokens in their styles
- Use the new package to evaluate Vanilla Extract for LaunchPad styles
- Add ADRs for styling decisions
Check out vars stories.
> feat: add vars package

- .changeset/lazy-meals-drum.md
- packages/chip/src/styles/Chip.module.css
Chip's icons are currently not centered which does not match with [design mocks](https://www.figma.com/file/ITlrRueSW0eYdUp7acr9Xi/LaunchPad?type=design&node-id=13919-73672&mode=design&t=OE0Itam0czr6C5q3-0)
I adjusted styles so that icons are centered in Chip.
Before:
After:
Visually
> fix: icon alignment for chip

- .changeset/smooth-clouds-chew.md
- packages/form/src/TextField.tsx
- packages/form/stories/FormField.stories.tsx
- If `autoComplete = "off"` for `TextField` input, 1Password will not inject autofill options and icons to the field
- I tried to implement this for LastPass as well, but recent updates disabled the fix, so as of now, there is no option to disable LastPass :(
Without fix:
With Password manager disabled:
- manual
> fix(textField): disable password managers from adding autofill icon to input

- .changeset/slow-lions-judge.md
- .storybook/styles.css
- packages/alert/src/styles/Alert.module.css
- packages/avatar/src/styles/Avatar.module.css
- packages/banner/src/styles/Banner.module.css
- packages/button/src/styles/Button.css
- packages/button/src/styles/ButtonVariables.css
- packages/chip/src/styles/Chip.module.css
- packages/clipboard/src/styles/CopyCodeButton.module.css
- packages/filter/src/styles/Filter.module.css
- packages/form/src/styles/Form.module.css
- packages/markdown/src/styles/Markdown.module.css
- packages/menu/src/styles/Menu.css
- packages/modal/src/styles/Modal.module.css
- packages/navigation/src/styles/Navigation.module.css
- packages/popover/src/styles/Popover.module.css
- packages/progress-bubbles/src/styles/ProgressBubbles.module.css
- packages/select/src/styles/Select.module.css
- packages/slider/src/styles/Slider.module.css
- packages/snackbar/src/styles/Snackbar.module.css
- packages/split-button/src/styles/SplitButton.css
- packages/tab-list/src/styles/TabList.module.css
- packages/toast/src/styles/Toast.module.css
- packages/toggle/src/styles/Toggle.module.css
- packages/tokens/src/color-aliases.yaml
- packages/tokens/src/color-primitives.yaml
- packages/tokens/stories/theme.stories.tsx
- packages/tooltip/src/styles/Tooltip.module.css
Tokens with multiple variants have not used a suffix to denote the `default` state of the token. This makes them difficult to implement in Figma and reference in the `vars` package for Vanilla Extract. For example, now instead of `vars.color.text.ui.primary[' ']` the token can be accessed via `vars.color.text.ui.primary.base` for better DX.
> refactor(tokens)!: add base suffix

- .changeset/cuddly-cows-applaud.md
- CONTRIBUTING.md
- packages/icons/README.md
- packages/icons/src/Icon.tsx
- packages/icons/src/context.ts
- packages/icons/src/img/sprite.svg
For consumers hosting static assets in a cdn or different domain we should allow them to inject the sprite into the document and have `Icon` access it there. Avoid id collisions by adding a `lp-icon` prefix to all symbols.
> feat(icons): add unique id prefix and allow empty path

- .changeset/old-bears-rescue.md
- packages/markdown/src/Markdown.tsx
- packages/markdown/src/utils.ts
Use es6 imports for `isomorphic-dompurify`.
> refactor(markdown): use es6 imports for isomorphic-dompurify

- .changeset/chatty-tables-attend.md
- .storybook/styles.css
- apps/remix/app/data.server.ts
- apps/remix/app/routes/components.inline-edit.tsx
- cypress.config.ts
- nyc.config.js
- package.json
- packages/core/package.json
- packages/core/src/index.ts
- packages/inline-edit/README.md
- packages/inline-edit/__tests__/InlineEdit.cy.tsx
- packages/inline-edit/__tests__/InlineEdit.spec.tsx
- packages/inline-edit/package.json
- packages/inline-edit/src/InlineEdit.tsx
- packages/inline-edit/src/index.ts
- packages/inline-edit/src/styles/InlineEdit.css.ts
- packages/inline-edit/stories/InlineEdit.stories.tsx
- packages/inline-edit/tsconfig.build.json
- pnpm-lock.yaml
- tsconfig.json
- vite.config.ts
Add `inline-edit` package to display and allow inline editing of a form elements:
- Use props `defaultValue` and `onConfirm` to handle state management of the value to edit
- Have children act as the "read" view of the component
- Hide edit icon button and wrap children with a React Aria button when `hideEdit` is true
- Implement focus management to ensure focus is directed correctly when toggling between read and edit mode
- Use `renderInput` prop to allow passing a custom `TextField` or `TextArea` component
- Add handlers for edit, cancel, and confirm actions
- Use prop `isEditing` to allow full control over the read and edit modes
- Add `@vanilla-extract/css` as a peer dependency for prop `layout` variant types
- Use `useFocusWithin` to cancel edit on blur …
> feat: add inline-edit package

- renovate.json
Since [React Aria releases](https://react-spectrum.adobe.com/releases/2023-08-09.html) can include patch updates, we want to include those to ensure all versions specified in package dependencies are compatible.
> ci: include react aria patches for renovate

- .changeset/moody-kiwis-double.md
- CONTRIBUTING.md
- packages/data-table/__tests__/DataTable.spec.tsx
- packages/data-table/src/DataTable.tsx
- packages/data-table/src/styles/DataTable.css.ts
- packages/data-table/stories/DataTable.stories.tsx
Enable column resizing via `allowsResizing` prop for `Column` inspired by the [React Aria example](https://react-spectrum.adobe.com/react-aria/useTable.html#resizable-columns).
Interact with [Resizable Columns story](https://626696a2018c1f004a1cde86-wtqnahuzso.chromatic.com/?path=/story/components-datatable--resizable-columns)
> feat(data-table): add column resizing

- .changeset/dull-elephants-wink.md
- packages/form/package.json
- packages/form/src/IconField.tsx
- packages/form/src/styles/Form.module.css
- packages/inline-edit/src/InlineEdit.tsx
- packages/inline-edit/stories/InlineEdit.stories.tsx
- pnpm-lock.yaml
Allow `InlineEdit` to render `IconField`. Add `tooltip` and `renderIconLast` props to `IconField`.
> feat(inline-edit): allow to render `IconField`

- .changeset/shaggy-ads-promise.md
- packages/alert/__tests__/Alert.spec.tsx
- packages/alert/src/Alert.tsx
- packages/alert/src/styles/Alert.module.css
- packages/alert/stories/Alert.stories.tsx
- packages/icons/src/StatusIcon.tsx
Supporting "notification" styles on Alert, including flare, with optional action button and link
Default flair notification style
Strong flair notification style (dark/light are the same)
> feat: support 'notification' alert + action elements

- .changeset/quick-apples-happen.md
- packages/tokens/README.md
- packages/tokens/build.ts
- packages/tokens/package.json
- packages/tokens/sd.config.js
- packages/tokens/src/color-aliases.yaml
- pnpm-lock.yaml
Prepare for color refresh changes that require `dark` variants of our global color tokens:
- Move color primitives to `themes.css`
- Update Style Dictionary to use `ts-node` via a `build.ts` file for type safety
- Add support for `dark` field on color primitives
> feat(tokens)!: move color primitives to themes.css

- .changeset/cyan-donkeys-change.md
- packages/button/src/styles/Button.module.css
- packages/button/src/styles/ButtonVariables.css
- packages/chip/src/styles/Chip.module.css
- packages/drawer/stories/Drawer.stories.tsx
- packages/modal/stories/Modal.stories.tsx
- packages/tag/src/Tag.tsx
- packages/tag/src/styles/Tag.module.css
- packages/tokens/build.ts
- packages/tokens/src/color-aliases.yaml
- packages/tokens/src/color-primitives.yaml
- packages/tokens/stories/tokens.stories.tsx
- playwright/a11y.spec.ts
Update color primitives and aliases for product refresh.
> refactor(tokens)!: update color primitives and aliases for product refresh

- .changeset/unlucky-stingrays-deny.md
- packages/icons/src/img/sprite.svg
- packages/icons/src/types.ts
Adds diamond and diamond-outline icons
> feat: add diamond and diamond-outline icons

- .changeset/quiet-emus-teach.md
- packages/alert/src/styles/Alert.module.css
- packages/avatar/src/styles/Avatar.module.css
- packages/button/src/styles/Button.module.css
- packages/button/src/styles/ButtonVariables.css
- packages/chip/src/styles/Chip.module.css
- packages/clipboard/src/styles/CopyCodeButton.module.css
- packages/counter/src/styles/Counter.module.css
- packages/data-table/stories/DataTable.stories.tsx
- packages/modal/src/styles/Modal.module.css
- packages/navigation/src/styles/Navigation.module.css
- packages/progress-bubbles/src/styles/ProgressBubbles.module.css
- packages/progress/src/styles/Progress.module.css
- packages/slider/src/styles/Slider.module.css
- packages/snackbar/src/styles/Snackbar.module.css
- packages/tag/src/styles/Tag.module.css
- packages/toast/src/styles/Toast.module.css
- packages/toggle/src/styles/Toggle.module.css
- packages/tokens/src/color-aliases.yaml
- packages/tokens/src/color-primitives.yaml
- packages/tooltip/src/styles/Tooltip.module.css
This PR updates our color refresh tokens to increase the 9 step color scales to 12 step. This allows for more text and icon options with accessible color pairings (goal from initial color refresh), but also gives us the range of colors we had under the previous color system that was lost with the initial refresh.
<details>
<summary>What needs to be updated in Gonfalon (expand to see details)</summary>
Have started to see how this will impact gonfalon and have started to document the vars that will need updated:
- `--white`
- `--black`
- `--color-app-bg`
- `--nav-background-color`
- `--app-nav-item-active-color`
- `--app-nav-item-color`
- `--header-background-color`
- `--color-bg-card`
- `--lp-component-toggle-color-text-on`
And some css module selectors that need to consume different lp …
> feat: Update color steps from 9 to 12

- docs/adr-008-component-foundation.md
Add an ADR going over tradeoffs of various solutions analyzed for #1015
> docs: add ADR for component foundation

- .changeset/weak-walls-drum.md
- package.json
- packages/box/src/styles/rainbow-sprinkles.css.ts
- packages/tokens/build.ts
- pnpm-lock.yaml
Add typography tokens to `box` package.
> feat(box): add typography tokens

- .changeset/strong-spiders-float.md
- packages/icons/src/img/sprite.svg
- packages/icons/src/types.ts
> feat: add 'circles' icon

- .changeset/polite-kings-return.md
- packages/menu/src/MenuItem.tsx
The current type of `tooltipOptions` on the `MenuItem` component is incorrect - it does not correctly reference the props of the tooltip component.
> fix: use proper type for exposing tooltip options on MenuItem

- .storybook/main.ts
- .storybook/modes.ts
- .storybook/preview.tsx
- package.json
- packages/alert/src/styles/Alert.module.css
- packages/clipboard/stories/CopyToClipboard.stories.tsx
- packages/core/stories/getting-started.stories.mdx
- packages/drawer/stories/Drawer.stories.tsx
- packages/icons/stories/Icon.stories.tsx
- packages/modal/stories/Modal.stories.tsx
- packages/navigation/stories/Navigation.stories.tsx
- pnpm-lock.yaml
Use [Story modes](https://www.chromatic.com/docs/modes/) and the [themes addon](https://storybook.js.org/addons/@storybook/addon-themes/) to handle snapshots in Chromatic.
> refactor: use storybook modes for chromatic

- .changeset/nasty-panthers-appear.md
- apps/remix/app/data.server.ts
- apps/remix/app/routes/rac.tooltip.tsx
- packages/components/__tests__/Tooltip.spec.tsx
- packages/components/src/Button.tsx
- packages/components/src/ButtonGroup.tsx
- packages/components/src/IconButton.tsx
- packages/components/src/LinkButton.tsx
- packages/components/src/ProgressBar.tsx
- packages/components/src/Tooltip.tsx
- packages/components/src/index.ts
- packages/components/src/styles/Tooltip.module.css
- packages/components/stories/Tooltip.stories.tsx
- packages/core/stories/getting-started.stories.mdx
- packages/tokens/src/color-aliases.yaml
- packages/tokens/stories/theme.stories.tsx
- stylelint.config.js
Add `Tooltip` and `TooltipTrigger`.
> feat(components): add `Tooltip` and `TooltipTrigger`

- .changeset/itchy-lions-jog.md
- .github/workflows/chromatic.yml
- .storybook/main.ts
- .storybook/preview.tsx
- packages/components/src/Button.tsx
- packages/components/src/IconButton.tsx
- packages/components/src/LinkButton.tsx
- packages/components/src/ProgressBar.tsx
- packages/components/src/Tooltip.tsx
- packages/components/src/styles/Button.module.css
- packages/components/stories/Button.stories.tsx
To [style states consistently](https://react-spectrum.adobe.com/react-aria/styling.html#states) across mouse, touch, and keyboard use the RAC data attributes instead of pseudo selectors. Use [composeRenderProps](https://github.com/adobe/react-spectrum/blob/main/starters/tailwind/src/Button.tsx) from RAC to support classNames with functions which receive states for styling. For button stories with multiple states, replace use of `storybook-addon-pseudo-states` with [Storybook interactions](https://storybook.js.org/docs/essentials/interactions) to trigger states.
> refactor(components): replace pseudo selectors with RAC data attributes

- .changeset/smart-terms-refuse.md
- .storybook/preview.tsx
- packages/components/src/index.ts
- packages/components/src/styles/Modal.module.css
- packages/components/src/styles/Popover.module.css
- packages/components/src/styles/Tooltip.module.css
- packages/components/src/styles/themes.css
Use [light-dark() color function](https://lightningcss.dev/transpilation.html#light-dark()-color-function) to minimize redundancy and avoid custom property bloat.
> feat(components): use light-dark function

- .changeset/gentle-trainers-crash.md
- packages/components/src/styles/Group.module.css
To avoid border radius on highlighted text.
> fix(components): unset border radius for `Input` in `Group`

- .changeset/rich-cats-pay.md
- packages/components/src/styles/Checkbox.module.css
Prevent `Checkbox` from shrinking in flex containers.
> fix(components): prevent checkbox from shrinking

- package.json
- playwright.config.ts
- pnpm-lock.yaml
Simplify `e2e:a11y` command for local dev by using [Playwright's web server](https://playwright.dev/docs/test-webserver) option.
> refactor: simplify running a11y tests locally

- .changeset/gentle-bobcats-teach.md
- packages/components/src/Button.tsx
- packages/components/src/ButtonGroup.tsx
- packages/components/src/IconButton.tsx
- packages/components/src/Link.tsx
- packages/components/src/LinkButton.tsx
- packages/components/src/Menu.tsx
- packages/components/src/Modal.tsx
- packages/components/src/Popover.tsx
- packages/components/src/ProgressBar.tsx
- packages/components/src/Switch.tsx
- packages/components/src/TagGroup.tsx
- packages/components/src/Tooltip.tsx
[Use interface instead of intersection](https://github.com/microsoft/TypeScript/wiki/Performance#preferring-interfaces-over-intersections). Addresses a bug I ran into where both types had incompatible property `variant` and the end result was undesired. This is because intersection recursively merges. From now on we'll use `interface` to be strict and explicit.
> fix(components): use interface instead of intersection

- .changeset/wicked-moles-knock.md
- packages/components/src/Popover.tsx
- packages/components/src/styles/Popover.module.css
Correct `ComboBox` popover styles since `--trigger-width` is based off the `Input` size. We use `Group` with input styles so we need to adjust things accordingly.
> fix(components): correct `ComboBox` popover size and position

- .changeset/shaggy-planets-smell.md
- packages/components/src/Checkbox.tsx
- packages/components/src/Radio.tsx
- packages/components/src/Switch.tsx
- packages/components/src/TagGroup.tsx
Use the `composeRenderProps` util to ensure consumers have access to [render props](https://react-spectrum.adobe.com/react-aria/styling.html#render-props) on applicable components. Helpful for things like adding tooltips or popovers to components that support hover/focus.
> fix(components): ensure render props can be used as children

- .changeset/chatty-clocks-bake.md
- packages/components/__tests__/TextField.spec.tsx
- packages/components/src/TextField.tsx
Set `Group` context within `TextField` ([like SearchField does](https://github.com/adobe/react-spectrum/blob/main/packages/react-aria-components/src/SearchField.tsx#L100)) using [Provider](https://react-spectrum.adobe.com/react-aria/advanced.html#provider) to improve DX.
> feat(components): set `Group` context within `TextField`

- playwright/a11y.spec.ts
Ensure RAC portals are included in axe scans by using the `[data-rac]` selector that every RAC renders.
Run the Playwright test in [UI mode](https://playwright.dev/docs/test-ui-mode) and log the nodes from the `passes` field within the scan results.
> fix: ensure RAC portals are included in axe scans

- .changeset/eleven-cooks-move.md
- packages/components/__tests__/Tooltip.spec.tsx
- packages/components/src/Tooltip.tsx
- packages/components/src/styles/TagGroup.module.css
- packages/components/src/styles/Tooltip.module.css
Ensure `Tooltip` content can be hovered to meet [a11y requirements](https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus.html).
Open a tooltip and notice you can hover to the content without it closing.
> fix(components): ensure `Tooltip` content can be hovered

- .changeset/pretty-snakes-notice.md
- packages/components/src/Modal.tsx
Make `Modal` dismissable by default.
> feat(components): make `Modal` dismissable by default

- .editorconfig
- nx.json
Add a `.editorconfig` so that our code is formatted as expected when viewed via GitHub and a user does not have their tab size configured. Helps our case since we use [tabs instead of spaces](https://twitter.com/Rich_Harris/status/1541761871585464323) and GitHub defaults to a tab size of 8.
> chore: add editorconfig

- .changeset/honest-geckos-think.md
- packages/components/src/ButtonGroup.tsx
- packages/components/src/styles/ButtonGroup.module.css
- packages/components/stories/ButtonGroup.stories.tsx
Use `Group` in `ButtonGroup` for better accessibility. Also add a story to show how to create a split button with the component.
> refactor(components): use `Group` in `ButtonGroup`

- .changeset/curly-bottles-marry.md
- packages/alert/src/styles/Alert.module.css
Address issue in Gonfalon where button styles are loaded after alert resulting in improper alignment. Once Alert gets rewritten with RAC and added to `components` these sort of issues won't happen.
> fix(alert): bump close specificity

- .changeset/kind-turtles-mix.md
- packages/components/src/Checkbox.tsx
- packages/components/src/Menu.tsx
- packages/components/src/Radio.tsx
- packages/components/src/styles/Checkbox.module.css
- packages/components/src/styles/Header.module.css
- packages/components/src/styles/Menu.module.css
- packages/components/src/styles/Radio.module.css
- packages/components/src/styles/RadioGroup.module.css
- packages/components/stories/Menu.stories.tsx
- packages/components/stories/Modal.stories.tsx
- packages/components/stories/Popover.stories.tsx
- packages/components/stories/Tooltip.stories.tsx
Update `Menu` selection states to display radio and checkbox visuals. To avoid nested interactive elements violations we can extract the inner content of `Checkbox` and `Radio` to display in menu items.
> fix(components): update `Menu` selection states

- .changeset/twelve-toes-fail.md
- packages/components/src/styles/Popover.module.css
Adjust styles for `OverlayArrow` to account for removing the border from `Popover`.
> fix(components): adjust styles for `OverlayArrow`

- .changeset/clean-dodos-laugh.md
- packages/components/src/styles/ListBox.module.css
We want most styles from `Menu` except the max width.
> fix(components): remove max-width on `ListBox`

- .changeset/gentle-ties-rule.md
- packages/components/package.json
- packages/components/src/ComboBox.tsx
- packages/components/src/Popover.tsx
- packages/components/src/styles/Popover.module.css
- packages/components/stories/ComboBox.stories.tsx
- pnpm-lock.yaml
Set `Popover` trigger in `ComboBox` to `Group` instead of `Input` to ensure the popover is sized and positioned correctly. This requires us to emulate a bit of their logic and define a separate context to pass to popover.
> fix(components): set `Popover` trigger in `ComboBox` to `Group` instead of `Input`

- .changeset/young-badgers-speak.md
- .storybook/preview.tsx
- package.json
- packages/components/__tests__/LinkButton.spec.tsx
- packages/components/__tests__/LinkIconButton.spec.tsx
- packages/components/global.d.ts
- packages/components/package.json
- packages/components/src/Link.tsx
- packages/components/src/RouterProvider.tsx
- packages/components/src/index.ts
- packages/components/stories/Link.stories.tsx
- packages/components/stories/LinkButton.stories.tsx
- packages/components/stories/LinkIconButton.stories.tsx
- packages/navigation/stories/Navigation.stories.tsx
- pnpm-lock.yaml
Use `href` and `routerOptions` with `RouterProvider` for links. This ensures state and other options are passed properly when using `react-router`.
> fix(components)!: use `href` and `routerOptions` with `RouterProvider` for links

- .changeset/two-timers-tell.md
- packages/components/src/Link.tsx
Add `DOMProps` to `LinkProps` to allow `id` on RAC links.
> fix(components): add `DOMProps` to `LinkProps`

- .github/CODEOWNERS
Adds Antonio and Matthew to code owners of icon package
Should probably do this in terraform, but can do that as followup
> chore: add designers to icon package CODEOWNERS

- .changeset/metal-cougars-tease.md
- packages/components/src/ListBox.tsx
- packages/components/src/styles/ListBox.module.css
- packages/components/src/styles/Select.module.css
Adjust `ListBox` styles to ensure descriptions wrap and items account for check mark space.
> fix(components): adjust `ListBox` styles

- .github/CODEOWNERS
Adds fe team to icons dir as code owners to not block on Antonio and Matthew
> fix: update CODEOWNERS for icons dir

- .changeset/good-rivers-ring.md
- packages/components/__tests__/Popover.spec.tsx
- packages/components/package.json
- packages/components/src/Popover.tsx
- packages/components/src/index.ts
- packages/components/src/styles/Popover.module.css
- packages/components/stories/Popover.stories.tsx
- pnpm-lock.yaml
Add `HoverTrigger` to support hover as a trigger for `Popover`. Provides UX similar [to this component](https://ui.shadcn.com/docs/components/navigation-menu). Hover toggles open state as well as clicks.
> feat(components): add `HoverTrigger`

- .changeset/angry-rules-cheat.md
- packages/components/src/styles/Input.module.css
Adjust `Input` focus outline offset to match updates from #1275.
> fix(components): adjust `Input` focus outline offset
